In [232]:
_author_ = 'Rahul-Chowdhury'
import pandas as pd
import sys
from collections import defaultdict
print(sys.version)

3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]

In [225]:
target_url = ("https://archive.ics.uci.edu/ml/machine-learning-databases/zoo/zoo.data")
zooData = pd.read_csv(target_url,header=None, prefix = "V")
#zooData = pd.DataFrame([{'V0':0,'V1':2, 'V2':1},{'V0':0,'V1':2, 'V2':1},{'V0':0,'V1':2, 'V2':1}])
print(zooData.head())

         V0  V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  V11  V12  V13  V14  V15  \
0  aardvark   1   0   0   1   0   0   1   1   1    1    0    0    4    0    0
1  antelope   1   0   0   1   0   0   0   1   1    1    0    0    4    1    0
2      bass   0   0   1   0   0   1   1   1   1    0    0    1    0    1    0
3      bear   1   0   0   1   0   0   1   1   1    1    0    0    4    0    0
4      boar   1   0   0   1   0   0   1   1   1    1    0    0    4    1    0

   V16  V17
0    1    1
1    1    1
2    0    4
3    1    1
4    1    1

In [226]:
k = len(list(zooData['V17'].unique())) #counting the number of classes in the last column
print(k)
zooData = zooData.drop(zooData.columns[[0, 17]], axis=1) #removing 1st and last column
zooData.head(10)

#def MMeR(U,k):

7

   V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  V11  V12  V13  V14  V15  V16
0   1   0   0   1   0   0   1   1   1    1    0    0    4    0    0    1
1   1   0   0   1   0   0   0   1   1    1    0    0    4    1    0    1
2   0   0   1   0   0   1   1   1   1    0    0    1    0    1    0    0
3   1   0   0   1   0   0   1   1   1    1    0    0    4    0    0    1
4   1   0   0   1   0   0   1   1   1    1    0    0    4    1    0    1
5   1   0   0   1   0   0   0   1   1    1    0    0    4    1    0    1
6   1   0   0   1   0   0   0   1   1    1    0    0    4    1    1    1
7   0   0   1   0   0   1   0   1   1    0    0    1    0    1    1    0
8   0   0   1   0   0   1   1   1   1    0    0    1    0    1    0    0
9   1   0   0   1   0   0   0   1   1    1    0    0    4    0    1    0

In [244]:
equiv_class_dict = {} #dictionary storing equiv classes for all attribute
for col in zooData:
    equiv_class_dict[col] =list(zooData.groupby([col]))

def roughness(col_name1, col_name2, val):
     arr = equiv_class_dict[col_name2] #group equiv classes according to column2
     target_set = zooData[zooData[col_name1] == val].index.tolist() #calculating target set for each unique value in column1
     lower_approx = []
     upper_approx = []
     for name,group in arr:
       selected_list = list(group.index)
       if(set(selected_list).issubset(target_set)): #if a subset, then append to lower_approx
            lower_approx.append(selected_list)
       if(set(selected_list) & set(target_set)): #if intersection is not null, then append to upper_approx
            upper_approx.append(selected_list)
     lower_approx_count = sum(map(len, lower_approx)) #count the no. of elements in lower_approx
     upper_approx_count = sum(map(len, upper_approx))
     roughness = 1 - (lower_approx_count/upper_approx_count) # return roughness for a(i) = alpha
     return roughness 
min_mean_roughness = {} #array to store the minimum of average of roughness of each attr
roughness_list_dict = defaultdict(dict)
for col1 in zooData:
    values_in_col_name1 =  list(zooData[col1].unique()) #extracting each unique value in column1
    mean_roughness = [] #list for mean roughness for a(i) = alpha
    for val in values_in_col_name1:
        roughness_list = [] #array of a(i) = alpha w.r.t. other columns 
        for col2 in zooData:
            if(col1!= col2): #not to be compared with itself
              roughness_list.append(roughness(col1 , col2, val))
        mean_roughness.append(sum(roughness_list)/float(len(roughness_list)))
        roughness_list_dict[col1][val] = sum(roughness_list)/float(len(roughness_list))
    min_mean_roughness[col1]=(min(mean_roughness))
for key in min_mean_roughness:
    print(key, min_mean_roughness[key])

V6 0.9881188118811882
V10 0.8975115511551156
V11 0.9412541254125413
V12 0.856105610561056
V8 0.9663366336633664
V15 0.9980198019801979
V13 0.9867986798679867
V1 0.9709570957095709
V5 0.9326732673267327
V4 0.9471947194719472
V14 0.9867986798679867
V7 0.9980198019801979
V16 0.9927392739273928
V2 0.7683168316831683
V3 0.9795379537953796
V9 0.8877962796279629
V2
0
     V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  V11  V12  V13  V14  V15  V16
11    0   1   1   0   1   0   0   0   1    1    0    0    2    1    1    0
16    0   1   1   0   1   0   1   0   1    1    0    0    2    1    0    0
20    0   1   1   0   1   0   0   0   1    1    0    0    2    1    1    0
21    0   1   1   0   1   1   0   0   1    1    0    0    2    1    0    0
23    0   1   1   0   1   0   0   0   1    1    0    0    2    1    0    1
33    0   1   1   0   1   1   1   0   1    1    0    0    2    1    0    0
37    0   1   1   0   1   0   1   0   1    1    0    0    2    1    0    0
41    0   1   1   0   0   0   1   0   1    1    0    0    2    1    0    0
43    0   1   1   0   1   0   0   0   1    1    0    0    2    1    0    0
56    0   1   1   0   0   0   0   0   1    1    0    0    2    1    0    1
57    0   1   1   0   1   0   0   0   1    1    0    0    2    1    1    0
58    0   1   1   0   0   1   1   0   1    1    0    0    2    1    0    1
59    0   1   1   0   1   0   0   0   1    1    0    0    2    1    0    0
71    0   1   1   0   0   0   1   0   1    1    0    0    2    1    0    1
78    0   1   1   0   1   1   1   0   1    1    0    0    2    1    0    0
79    0   1   1   0   1   1   1   0   1    1    0    0    2    1    0    0
83    0   1   1   0   1   0   0   0   1    1    0    0    2    1    0    0
87    0   1   1   0   1   1   0   0   1    1    0    0    2    1    0    1
95    0   1   1   0   1   0   1   0   1    1    0    0    2    1    0    1
100   0   1   1   0   1   0   0   0   1    1    0    0    2    1    0    0

In [245]:
min_roughness_attr = min(min_mean_roughness, key=min_mean_roughness.get) #find the attr with minimum roughness
min_roughness_attr_value = min(roughness_list_dict[min_roughness_attr]) #find the min. value of min_roughness_attr for which alpha is minimum
print(min_roughness_attr)
print(min_roughness_attr_value)
cluster1 = zooData.loc[zooData[min_roughness_attr] == min_roughness_attr_value]
cluster1_distance = cluster_distance(cluster1)
cluster2 = zooData.loc[zooData[min_roughness_attr] != min_roughness_attr_value]
cluster2_distance = cluster_distance(cluster2)
print(cluster2)
def cluster_distance(cluster):
    distance = 0
    for col in cluster:

V2
0
     V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  V11  V12  V13  V14  V15  V16
11    0   1   1   0   1   0   0   0   1    1    0    0    2    1    1    0
16    0   1   1   0   1   0   1   0   1    1    0    0    2    1    0    0
20    0   1   1   0   1   0   0   0   1    1    0    0    2    1    1    0
21    0   1   1   0   1   1   0   0   1    1    0    0    2    1    0    0
23    0   1   1   0   1   0   0   0   1    1    0    0    2    1    0    1
33    0   1   1   0   1   1   1   0   1    1    0    0    2    1    0    0
37    0   1   1   0   1   0   1   0   1    1    0    0    2    1    0    0
41    0   1   1   0   0   0   1   0   1    1    0    0    2    1    0    0
43    0   1   1   0   1   0   0   0   1    1    0    0    2    1    0    0
56    0   1   1   0   0   0   0   0   1    1    0    0    2    1    0    1
57    0   1   1   0   1   0   0   0   1    1    0    0    2    1    1    0
58    0   1   1   0   0   1   1   0   1    1    0    0    2    1    0    1
59    0   1   1   0   1   0   0   0   1    1    0    0    2    1    0    0
71    0   1   1   0   0   0   1   0   1    1    0    0    2    1    0    1
78    0   1   1   0   1   1   1   0   1    1    0    0    2    1    0    0
79    0   1   1   0   1   1   1   0   1    1    0    0    2    1    0    0
83    0   1   1   0   1   0   0   0   1    1    0    0    2    1    0    0
87    0   1   1   0   1   1   0   0   1    1    0    0    2    1    0    1
95    0   1   1   0   1   0   1   0   1    1    0    0    2    1    0    1
100   0   1   1   0   1   0   0   0   1    1    0    0    2    1    0    0